### ISSUE TITLE
Getting undefined error when the value is set to false. 

### ISSUE THREAD

**Issue by eqbal** [minichate/ember-cli-conditional-compile#29]
i'm using ember `2.5` and everything is working as expected when I define var as true, however when I define variable as false I'm having an error: 

```
Cannot read property 'ENABLE_FOO' of undefined
TypeError: Cannot read property 'ENABLE_FOO' of undefined
  at /myproject/node_modules/ember-cli-conditional-compile/index.js:63:64
  at Array.map (native)
  at Class.postprocessTree (/Users/info/code/mesitis/canopy-fresh/node_modules/ember-cli-conditional-compile/index.js:62:38)
  at /myproject/node_modules/ember-cli/lib/broccoli/ember-app.js:508:27
  at Array.forEach (native)
  at EmberApp.addonPostprocessTree (/myproject/node_modules/ember-cli/lib/broccoli/ember-app.js:506:23)
  at EmberApp.appAndDependencies (/myproject/node_modules/ember-cli/lib/broccoli/ember-app.js:1050:31)
  at EmberApp.javascript (/myproject/node_modules/ember-cli/lib/broccoli/ember-app.js:1161:34)
  at EmberApp.toArray (/myproject/node_modules/ember-cli/lib/broccoli/ember-app.js:1566:10)
  at EmberApp.toTree (/myproject/node_modules/ember-cli/lib/broccoli/ember-app.js:1588:30)
  at module.exports (/myproject/ember-cli-build.js:85:14)
  at Class.setupBroccoliBuilder (/myproject/node_modules/ember-cli/lib/models/builder.js:54:19)
  at Class.init (/myproject/node_modules/ember-cli/lib/models/builder.js:89:10)
  at Class.superWrapper [as init] (/myproject/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
  at Class (/myproject/node_modules/ember-cli/node_modules/core-object/core-object.js:32:33)
  at Class.run (/myproject/node_modules/ember-cli/lib/tasks/serve.js:15:19)
  at /myproject/node_modules/ember-cli/lib/commands/serve.js:64:24
  at tryCatch (/myproject/node_modules/rsvp/dist/rsvp.js:538:12)
  at invokeCallback (/myproject/node_modules/rsvp/dist/rsvp.js:553:13)
  at /myproject/node_modules/rsvp/dist/rsvp.js:628:16
  at flush (/myproject/node_modules/rsvp/dist/rsvp.js:2373:5)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

Please note that in my `environment.js` file : 

```
  var ENV = {
    featureFlags: {
      ENABLE_FOO: false
    },

```

If I turn it to true everything works as expected. 

Any help? thanks

**Comment by tehmaestro** [comment]
I get the same thing, did you manage to fix it? Thanks.

**Comment by jobackman** [comment]
Like @tehmaestro said this is because `includeDirByFlag` is undefined. 
I do like the readme and have an `includeDirByFlag` for every featureFlag I have, but as empty arrays:

```js
var ENV = {
    // other settings ...

    featureFlags: {
        ENABLE_FOO: true,
        ENABLE_BAR: true
    },
    includeDirByFlag: {
        ENABLE_FOO: [/pods\/foos/, /pods\/foo/],
        ENABLE_BAR: [],
    }
};
``` 

I suggest we close this issue and keep #26 open since it is the same problem.

**Comment by minichate** [comment]
Closing. Thanks!
